import type { Doador, Doacao, Coleta, BaixaColeta } from "./types"

export const mockDoadores: Doador[] = [
  {
    id: "DOA001",
    tipo: "PF",
    nome: "Maria Silva Santos",
    email: "maria.silva@email.com",
    telefone: "(11) 98765-4321",
    cep: "01310-100",
    endereco: {
      rua: "Avenida Paulista",
      numero: "1000",
      complemento: "Apto 123",
      bairro: "Bela Vista",
      cidade: "São Paulo",
      uf: "SP",
    },
    prioridade: "Alta",
    totalDoacoes: 5,
    ultimaDoacao: "2026-01-15",
    status: "Ativo",
    observacoes: "Doadora frequente, sempre disponível no período da manhã.",
    createdAt: "2025-06-10",
  },
  {
    id: "DOA002",
    tipo: "PF",
    nome: "João Pedro Oliveira",
    email: "joao.oliveira@email.com",
    telefone: "(11) 91234-5678",
    cep: "04538-132",
    endereco: {
      rua: "Rua Funchal",
      numero: "500",
      bairro: "Vila Olímpia",
      cidade: "São Paulo",
      uf: "SP",
    },
    prioridade: "Média",
    totalDoacoes: 3,
    ultimaDoacao: "2026-01-10",
    status: "Ativo",
    createdAt: "2025-08-22",
  },
  {
    id: "DOA003",
    tipo: "PJ",
    nome: "Empresa ABC Ltda",
    email: "contato@empresaabc.com",
    cep: "22041-080",
    endereco: {
      rua: "Rua Visconde de Pirajá",
      numero: "330",
      complemento: "Sala 201",
      bairro: "Ipanema",
      cidade: "Rio de Janeiro",
      uf: "RJ",
    },
    prioridade: "Alta",
    totalDoacoes: 8,
    ultimaDoacao: "2026-01-18",
    status: "Ativo",
    observacoes: "Prefere coletas às sextas-feiras.",
    createdAt: "2025-03-15",
  },
  {
    id: "DOA004",
    tipo: "PF",
    nome: "Carlos Eduardo Mendes",
    email: "carlos.mendes@email.com",
    telefone: "(21) 99876-5432",
    cep: "30130-000",
    endereco: {
      rua: "Praça Sete de Setembro",
      numero: "100",
      bairro: "Centro",
      cidade: "Belo Horizonte",
      uf: "MG",
    },
    prioridade: "Baixa",
    totalDoacoes: 1,
    ultimaDoacao: "2025-12-05",
    status: "Inativo",
    createdAt: "2025-11-20",
  },
  {
    id: "DOA005",
    tipo: "PJ",
    nome: "Instituto Solidário",
    email: "contato@institutosolidario.org",
    telefone: "(11) 95555-1234",
    cep: "01414-001",
    endereco: {
      rua: "Rua Oscar Freire",
      numero: "200",
      bairro: "Jardins",
      cidade: "São Paulo",
      uf: "SP",
    },
    prioridade: "Alta",
    totalDoacoes: 12,
    ultimaDoacao: "2026-01-20",
    status: "Ativo",
    observacoes: "Top doadora! Sempre com itens em ótimo estado.",
    createdAt: "2024-09-01",
  },
]

export const mockDoacoes: Doacao[] = [
  {
    id: "DON001",
    dataCreated: "2026-01-20",
    doadorId: "DOA005",
    doador: {
      nome: "Fernanda Lima Costa",
      email: "fernanda.costa@email.com",
    },
    tipoItem: "Roupas",
    condicaoItem: "Bom",
    modalidade: "Retirada",
    volume: "Médio",
    veiculoSugerido: "Carro",
    status: "Coleta agendada",
    endereco: {
      rua: "Rua Oscar Freire",
      numero: "200",
      bairro: "Jardins",
      cidade: "São Paulo",
      uf: "SP",
      cep: "01414-001",
    },
    itensDeclarados: "15 peças de roupa feminina, 10 peças infantis",
    quantidade: 25,
    agendamento: {
      data: "2026-01-22",
      periodo: "Manhã",
    },
    observacoes: "Interfone 201",
    atendente: "Ana Paula Silva",
  },
  {
    id: "DON002",
    dataCreated: "2026-01-19",
    doadorId: "DOA003",
    doador: {
      nome: "Ana Carolina Ferreira",
      email: "ana.ferreira@email.com",
    },
    tipoItem: "Livros",
    condicaoItem: "Bom",
    modalidade: "Ponto de coleta",
    volume: "Pequeno",
    veiculoSugerido: "Carro",
    status: "Confirmada",
    itensDeclarados: "30 livros infantis e didáticos",
    quantidade: 30,
    atendente: "Carlos Eduardo Santos",
  },
  {
    id: "DON003",
    dataCreated: "2026-01-18",
    doadorId: "DOA001",
    doador: {
      nome: "Maria Silva Santos",
      email: "maria.silva@email.com",
    },
    tipoItem: "Móveis",
    condicaoItem: "Não confirmado",
    modalidade: "Retirada",
    volume: "Muito grande",
    veiculoSugerido: "Van",
    status: "Em validação manual",
    endereco: {
      rua: "Avenida Paulista",
      numero: "1000",
      complemento: "Apto 123",
      bairro: "Bela Vista",
      cidade: "São Paulo",
      uf: "SP",
      cep: "01310-100",
    },
    itensDeclarados: "Sofá 3 lugares, mesa de jantar com 4 cadeiras",
    observacoes: "Moveis pesados, necessario equipe de 2 pessoas",
    atendente: "Mariana Oliveira",
  },
  {
    id: "DON004",
    dataCreated: "2026-01-17",
    doadorId: "DOA002",
    doador: {
      nome: "João Pedro Oliveira",
      email: "joao.oliveira@email.com",
    },
    tipoItem: "Eletrodomésticos",
    condicaoItem: "Precisa triagem",
    modalidade: "Retirada",
    volume: "Grande",
    veiculoSugerido: "Utilitário",
    status: "Coleta agendada",
    endereco: {
      rua: "Rua Funchal",
      numero: "500",
      bairro: "Vila Olímpia",
      cidade: "São Paulo",
      uf: "SP",
      cep: "04538-132",
    },
    itensDeclarados: "Geladeira, micro-ondas, liquidificador",
    agendamento: {
      data: "2026-01-23",
      periodo: "Tarde",
    },
    atendente: "Joao Pedro Costa",
  },
  {
    id: "DON005",
    dataCreated: "2026-01-15",
    doadorId: "DOA001",
    doador: {
      nome: "Maria Silva Santos",
      email: "maria.silva@email.com",
    },
    tipoItem: "Brinquedos",
    condicaoItem: "Bom",
    modalidade: "Retirada",
    volume: "Pequeno",
    veiculoSugerido: "Carro",
    status: "Coletada",
    endereco: {
      rua: "Avenida Paulista",
      numero: "1000",
      complemento: "Apto 123",
      bairro: "Bela Vista",
      cidade: "São Paulo",
      uf: "SP",
      cep: "01310-100",
    },
    itensDeclarados: "20 brinquedos variados, jogos de tabuleiro",
    quantidade: 20,
    agendamento: {
      data: "2026-01-16",
      periodo: "Manha",
    },
    atendente: "Fernanda Lima",
  },
  {
    id: "DON006",
    dataCreated: "2026-01-14",
    doadorId: "DOA004",
    doador: {
      nome: "Carlos Eduardo Mendes",
      email: "carlos.mendes@email.com",
    },
    tipoItem: "Outros",
    condicaoItem: "Bom",
    modalidade: "Ponto de coleta",
    volume: "Pequeno",
    veiculoSugerido: "Carro",
    status: "Cancelada",
    itensDeclarados: "Artigos de cozinha variados",
    observacoes: "Doador cancelou por motivos pessoais",
    atendente: "Ricardo Mendes",
  },
  {
    id: "DON007",
    dataCreated: "2026-01-21",
    doadorId: "DOA005",
    doador: {
      nome: "Fernanda Lima Costa",
      email: "fernanda.costa@email.com",
    },
    tipoItem: "Roupas",
    condicaoItem: "Bom",
    modalidade: "Retirada",
    volume: "Grande",
    veiculoSugerido: "Utilitário",
    status: "Pendente",
    endereco: {
      rua: "Rua Oscar Freire",
      numero: "200",
      bairro: "Jardins",
      cidade: "São Paulo",
      uf: "SP",
      cep: "01414-001",
    },
    itensDeclarados: "50 peças de roupa masculina e feminina",
    quantidade: 50,
    atendente: "Ana Paula Silva",
  },
]

export const mockColetas: Coleta[] = [
  {
    id: "COL001",
    doacaoId: "DON001",
    doadorNome: "Fernanda Lima Costa",
    doadorTelefone: "(11) 95555-1234",
    endereco: "Rua Oscar Freire, 200 - Jardins, São Paulo/SP",
    enderecoCompleto: {
      rua: "Rua Oscar Freire",
      numero: "200",
      bairro: "Jardins",
      cidade: "São Paulo",
      uf: "SP",
      cep: "01414-001",
    },
    volume: "Médio",
    veiculo: "Carro",
    dataAgendada: "2026-01-22",
    periodo: "Manhã",
    status: "Pendente",
    ordemRota: 1,
    itens: "15 peças de roupa feminina, 10 peças infantis",
    observacoes: "Interfone 201",
  },
  {
    id: "COL002",
    doacaoId: "DON004",
    doadorNome: "João Pedro Oliveira",
    doadorTelefone: "(11) 91234-5678",
    endereco: "Rua Funchal, 500 - Vila Olímpia, São Paulo/SP",
    enderecoCompleto: {
      rua: "Rua Funchal",
      numero: "500",
      bairro: "Vila Olímpia",
      cidade: "São Paulo",
      uf: "SP",
      cep: "04538-132",
    },
    volume: "Grande",
    veiculo: "Utilitário",
    dataAgendada: "2026-01-23",
    periodo: "Tarde",
    status: "Pendente",
    ordemRota: 2,
    itens: "Geladeira, micro-ondas, liquidificador",
  },
  {
    id: "COL003",
    doacaoId: "DON005",
    doadorNome: "Maria Silva Santos",
    doadorTelefone: "(11) 98765-4321",
    endereco: "Avenida Paulista, 1000, Apto 123 - Bela Vista, São Paulo/SP",
    enderecoCompleto: {
      rua: "Avenida Paulista",
      numero: "1000",
      complemento: "Apto 123",
      bairro: "Bela Vista",
      cidade: "São Paulo",
      uf: "SP",
      cep: "01310-100",
    },
    volume: "Pequeno",
    veiculo: "Carro",
    dataAgendada: "2026-01-16",
    periodo: "Manhã",
    status: "Coletada",
    itens: "20 brinquedos variados, jogos de tabuleiro",
  },
  {
    id: "COL004",
    doacaoId: "DON008",
    doadorNome: "Roberto Almeida",
    doadorTelefone: "(11) 97777-8888",
    endereco: "Rua Augusta, 800 - Consolação, São Paulo/SP",
    enderecoCompleto: {
      rua: "Rua Augusta",
      numero: "800",
      bairro: "Consolação",
      cidade: "São Paulo",
      uf: "SP",
      cep: "01305-000",
    },
    volume: "Pequeno",
    veiculo: "Carro",
    dataAgendada: "2026-01-19",
    periodo: "Manhã",
    status: "Atrasada",
    itens: "10 livros, 5 jogos de tabuleiro",
    diasAtrasado: 2,
    motivoAtraso: "Doador não estava em casa",
  },
  {
    id: "COL005",
    doacaoId: "DON009",
    doadorNome: "Patricia Souza",
    doadorTelefone: "(11) 96666-5555",
    endereco: "Alameda Santos, 1200 - Jardim Paulista, São Paulo/SP",
    enderecoCompleto: {
      rua: "Alameda Santos",
      numero: "1200",
      bairro: "Jardim Paulista",
      cidade: "São Paulo",
      uf: "SP",
      cep: "01418-100",
    },
    volume: "Grande",
    veiculo: "Van",
    dataAgendada: "2026-01-22",
    periodo: "Tarde",
    status: "Pendente",
    ordemRota: 3,
    itens: "2 bicicletas, 1 mesa de escritório",
  },
]

export const mockBaixas: BaixaColeta[] = [
  {
    id: "BAI001",
    coletaId: "COL003",
    doacaoId: "DON005",
    doadorNome: "Maria Silva Santos",
    dataColetaAgendada: "2026-01-16",
    dataBaixa: "2026-01-16T10:30:00",
    responsavel: "Carlos Operador",
    statusFinal: "Coletada",
    observacao: "Coleta realizada sem problemas",
    veiculo: "Carro",
  },
  {
    id: "BAI002",
    coletaId: "COL010",
    doacaoId: "DON010",
    doadorNome: "Lucas Martins",
    dataColetaAgendada: "2026-01-15",
    dataBaixa: "2026-01-15T15:45:00",
    responsavel: "Ana Operadora",
    statusFinal: "Coletada",
    veiculo: "Utilitário",
  },
  {
    id: "BAI003",
    coletaId: "COL011",
    doacaoId: "DON011",
    doadorNome: "Juliana Campos",
    dataColetaAgendada: "2026-01-14",
    dataBaixa: "2026-01-14T11:20:00",
    responsavel: "Carlos Operador",
    statusFinal: "Não coletada",
    observacao: "Endereço não localizado, doador não atendeu ligações",
    veiculo: "Carro",
  },
]

// KPI data
export const mockKPIs = {
  totalDoacoesMes: 47,
  coletasHoje: 3,
  coletasAtrasadas: 1,
  coletasPendentes: 5,
  totalDoadores: 156,
  doadoresAtivos: 142,
}
